@startuml
'https://plantuml.com/class-diagram
class CLiente{
    -task: Task
    -project: Project
}

abstract Project{

    - tag: String
    - task: <ArrayList>:Task
    -project <ArrayList>: Project
    -createProject(tag: String)
    +duracion()
    +startTask()
    +stopTask()


}
class childrenProject{

    - tag: String
    - task: <ArrayList>:Task
    -project <ArrayList>: Project
    -createProject(tag: String)
    +duracion()
    +startTask()
    +stopTask()


}

abstract Com {
   - dateInitial: LocalDateTime
   - dateFinal: LocalDateTime
   - duration: LocalDateTime

}
class Task {
   - tag: String
   - duration: LocalDateTime
    -createTask(tag: String)
    +duracion()
    +startTask()
    +stopTask()

}


Project"1" *-> "n"Task


@enduml