@startuml
'https://plantuml.com/class-diagram



class Client{
    -task: Task
    -project: Project

}
abstract Component{
    {abstract}-initialDate: LocalDateTime
    {abstract}-finalDate: LocalDateTime
    {abstract}- tag: String
    {abstract}- duration: LocalDateTime
    - task: <ArrayList>:Task
    -project <ArrayList>: Project
    -createProject(tag: String)
    -getProject()
     #duracion():LocalDateTime

}
class Project{
    - tag: String
    - task: <ArrayList>:Task
    -project <ArrayList>: Project
    #duracion():LocalDateTime
    +startTask()
    +stopTask()
}



class Task {
   - tag: String
   -interval:LocalDateTime[]
    -createTask(tag: String)
    #duration():LocalDateTime
    -startTask()
    -stopTask()

}
Component  <|-- Task
Component <|-- Project
Project *-> Component:children
Client --|> Component:component


@enduml